version: '3'

services:
  api:
    container_name: {{cookiecutter.project_name}}-api
    build:
      dockerfile: Dockerfile-dev
      context: .
    environment:
      - DD_SERVICE={{cookiecutter.project_name}}
      - DD_TRACE_ASGI_ANALYTICS_ENABLED=true
      - DATABASE_URL=postgresql://test:test@db:5432/{{cookiecutter.db_name}}
    volumes:
      - .:/app/
    ports:
      - "{{cookiecutter.api_port}}:{{cookiecutter.api_port}}"
{%- if cookiecutter.structure == "API + POSTGRES" -%}
  {% filter escape %}
    depends_on:
      - db
    links:
      - db
  {% endfilter %}
  db:
    container_name: {{cookiecutter.project_name}}-db
    image: postgres:10.13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: {{cookiecutter.db_name}}
{% endif %}