from setuptools import setup, find_packages

setup(name='{{cookiecutter.project_name}}',
      description="Build your brand new service!",
      author="Captalys Tech",
      author_email="desenvolvimento@captalys.com.br",
      license="BSD",
      keywords="captalys technology",
      packages=find_packages(),
      include_package_data=True,
      install_requires=["click==7.1.2",
                        "ddtrace==0.42.0",
                        "fastapi==0.61.1",
                        "h11==0.9.0",
                        "httptools==0.1.1",
                        "intervaltree==3.1.0",
                        "protobuf==3.13.0",
                        "psycopg2==2.8.6",
                        "pydantic==1.6.1",
                        "six==1.15.0",
                        "sortedcontainers==2.2.2",
                        "sqlalchemy==1.3.19",
                        "starlette==0.13.6",
                        "tenacity==6.2.0",
                        "uvicorn==0.11.8",
                        "uvloop==0.14.0",
                        "websockets==8.1"],
      zip_safe=False)
