from setuptools import setup, find_packages

setup(name='{{cookiecutter.project_name}}',
      description="Build your brand new service!",
      author="Captalys Tech",
      author_email="desenvolvimento@captalys.com.br",
      license="BSD",
      keywords="captalys technology",
      packages=find_packages(),
      include_package_data=True,
      install_requires=["aiohttp==3.6.2",
                        "async-timeout==3.0.1",
                        "attrs==20.2.0",
                        "chardet==3.0.4",
                        "click==7.1.2",
                        "coverage==5.3",
                        "ddtrace==0.41.2",
                        "fastapi==0.61.1",
                        "h11==0.9.0",
                        "httptools==0.1.1",
                        "idna==2.10",
                        "importlib-metadata==1.7.0",
                        "iniconfig==1.0.1",
                        "intervaltree==3.1.0",
                        "more-itertools==8.5.0",
                        "multidict==4.7.6",
                        "packaging==20.4",
                        "pluggy==0.13.1",
                        "protobuf==3.13.0",
                        "psycopg2==2.8.6",
                        "py==1.9.0",
                        "pydantic==1.6.1",
                        "pyparsing==2.4.7",
                        "pytest==6.0.2",
                        "python-dateutil==2.8.1",
                        "six==1.15.0",
                        "sortedcontainers==2.2.2",
                        "sqlalchemy==1.3.19",
                        "starlette==0.13.6",
                        "tenacity==6.2.0",
                        "toml==0.10.1",
                        "typing-extensions==3.7.4.3",
                        "uvicorn==0.11.8",
                        "uvloop==0.14.0",
                        "websockets==8.1",
                        "yarl==1.5.1",
                        "zipp==3.1.0"],
      zip_safe=False)
